"use client";
import { useMemo, useState } from "react";
import { scorePunta, calculateLoan } from "@/lib/credit";
function money(v:number){return new Intl.NumberFormat("es-UY",{style:"currency",currency:"UYU",maximumFractionDigits:0}).format(v)}
export default function ScorePage(){
 const [income,setIncome]=useState(50000),[amount,setAmount]=useState(8000),[months,setMonths]=useState(6),[years,setYears]=useState(3),[good,setGood]=useState(0),[late,setLate]=useState(0);
 const calc=useMemo(()=>calculateLoan(amount,60,months),[amount,months]);
 const result=useMemo(()=>scorePunta({income,requested:amount,monthlyPayment:calc.payment,employmentYears:years,priorGoodLoans:good,priorLateLoans:late}),[income,amount,calc.payment,years,good,late]);
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><div className="text-2xl font-bold">Créditos<span className="text-sky-600">Punta</span></div><a href="/" className="text-sm font-semibold">← Dashboard</a></div></header><div className="mx-auto max-w-6xl px-6 py-8"><h1 className="text-3xl font-bold">Score Punta</h1><p className="mt-1 text-slate-500">Motor de evaluación de demo. No constituye una decisión crediticia real.</p><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-bold">Datos</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Ingreso mensual",income,setIncome],["Monto solicitado",amount,setAmount],["Antigüedad laboral",years,setYears],["Préstamos buenos",good,setGood],["Préstamos con mora",late,setLate]].map(([label,value,setter]:any)=><label key={label} className="text-sm font-medium">{label}<input type="number" value={value} onChange={e=>setter(+e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2"/></label>)}<label className="text-sm font-medium">Plazo<select value={months} onChange={e=>setMonths(+e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2"><option value="3">3 meses</option><option value="6">6 meses</option><option value="9">9 meses</option><option value="12">12 meses</option></select></label></div></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="text-sm text-slate-500">Score Punta</div><div className="mt-2 text-5xl font-bold">{result.score}</div><div className="mt-3 inline-block rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">Riesgo {result.risk}</div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div><div className="text-sm text-slate-500">Cuota simulada</div><div className="mt-1 text-xl font-bold">{money(calc.payment)}</div></div><div><div className="text-sm text-slate-500">Monto máximo sugerido</div><div className="mt-1 text-xl font-bold">{money(result.maxSuggested)}</div></div></div><div className="mt-8 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">El score es experimental y deberá validarse con datos, criterios de no discriminación, documentación y revisión legal antes de utilizarse para decisiones reales.</div></section></div></div></main>
}
