"use client";

import { useMemo, useState } from "react";

function formatUYU(value:number){return new Intl.NumberFormat("es-UY",{style:"currency",currency:"UYU",maximumFractionDigits:0}).format(value)}

export default function PrestamosPage(){
 const [amount,setAmount]=useState(8000); const [months,setMonths]=useState(6); const [annual,setAnnual]=useState(60);
 const result=useMemo(()=>{const r=annual/100/12; const payment=r===0?amount/months:amount*r/(1-Math.pow(1+r,-months)); const total=payment*months; return {payment,total,interest:total-amount};},[amount,months,annual]);
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><div className="text-2xl font-bold">Créditos<span className="text-sky-600">Punta</span></div><a href="/" className="text-sm font-semibold text-slate-600">← Dashboard</a></div></header><div className="mx-auto max-w-6xl px-6 py-8"><h1 className="text-3xl font-bold">Simulador de crédito</h1><p className="mt-1 text-slate-500">Herramienta interna de simulación. La tasa es configurable y no representa una tasa autorizada.</p><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-bold">Parámetros</h2><label className="mt-6 block text-sm font-medium">Monto: {formatUYU(amount)}</label><input type="range" min="4000" max="12000" step="500" value={amount} onChange={e=>setAmount(+e.target.value)} className="mt-3 w-full"/><div className="mt-6 grid grid-cols-2 gap-4"><div><label className="text-sm font-medium">Plazo</label><select value={months} onChange={e=>setMonths(+e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2"><option value="3">3 meses</option><option value="6">6 meses</option><option value="9">9 meses</option><option value="12">12 meses</option></select></div><div><label className="text-sm font-medium">Tasa anual simulada</label><input type="number" min="0" value={annual} onChange={e=>setAnnual(+e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2"/></div></div><div className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Esta tasa es solamente para simulación. Antes de operar debemos determinar la tasa máxima legal y el costo financiero total aplicable.</div></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-bold">Resultado</h2><div className="mt-6 grid gap-4 sm:grid-cols-3"><div><div className="text-sm text-slate-500">Cuota</div><div className="mt-1 text-2xl font-bold">{formatUYU(result.payment)}</div></div><div><div className="text-sm text-slate-500">Total</div><div className="mt-1 text-2xl font-bold">{formatUYU(result.total)}</div></div><div><div className="text-sm text-slate-500">Intereses</div><div className="mt-1 text-2xl font-bold">{formatUYU(result.interest)}</div></div></div><div className="mt-8 border-t pt-6"><h3 className="font-semibold">Calendario estimado</h3><div className="mt-3 divide-y">{Array.from({length:months},(_,i)=><div key={i} className="flex justify-between py-3 text-sm"><span>Cuota {i+1}</span><span className="font-semibold">{formatUYU(result.payment)}</span></div>)}</div></div><button disabled className="mt-6 w-full cursor-not-allowed rounded-lg bg-slate-300 px-4 py-3 font-semibold text-slate-600">Crear solicitud — próximamente</button></section></div></div></main>
}
